name: Mirror SVN to Git

on:
  workflow_dispatch: # Allows to run manually also

jobs:
  mirrorSVN:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        path: git-repo

    - name: Install SVN
      run: sudo apt-get install -y subversion

    - name: Install Git LFS
      run: |
        sudo apt-get install -y git-lfs
        git lfs install
        
    - name: Configure Checked-Out Git repository
      run: |
        cd git-repo
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
 
    - name: Set Branch Name
      run: |
        echo "BRANCH_NAME=automation-branch-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo "Done Setting Name As: ${{ env.BRANCH_NAME }} or $BRANCH_NAME"

    - name: Confirm Name
      run: |
        echo "Done Setting Name As: ${{ env.BRANCH_NAME }}"

    - name: Clone SVN repository
      run: svn checkout --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} https://svn.code.sf.net/p/cbecc-com/code/branches/CBECC-Com_MFamRestructure/ svn-repo
  
    - name: Copy files from SVN to Git
      run: |
        cp -R svn-repo/* git-repo/

    - name: Check to see if there are new commits
      run: |
        cd git-repo
        if [ -z "$(git status --porcelain)" ]; then
          echo "HAS_UPDATES=yes" >> $GITHUB_ENV
        else
          echo "HAS_UPDATES=no" >> $GITHUB_ENV
        fi
        echo "Does repo have updates: ${{ env.HAS_UPDATES }} or $HAS_UPDATES"

    - name: Commit and push SVN to Git If Changes
      if: ${{ env.HAS_UPDATES }} == 'yes'
      run: |
        cd git-repo
        echo "Commits found"
        git add .
        git commit -m "Automated Mirror from SVN"
        
    - name: Create Pull Request
      if: ${{ env.HAS_UPDATES }} == 'yes'
      uses: peter-evans/create-pull-request@v7
      with:
        path: git-repo
        branch: ${{ env.BRANCH_NAME }}
        title: "Automated Pull Request"
        body: "This pull request was created automatically by GitHub Actions. It mirrors the SVN repository to Git with no history."