name: Mirror SVN to Git

on:
  workflow_dispatch: # Allows to run manually also

jobs:
  mirrorSVN:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        path: git-repo

    - name: Install SVN
      run: sudo apt-get install -y subversion

    - name: Install Git LFS
      run: |
        sudo apt-get install -y git-lfs
        git lfs install
        
    - name: Configure Checked-Out Git repository
      run: |
        cd git-repo
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git checkout -b test-mirror || git checkout test-mirror

    - name: Clone SVN repository
      run: svn checkout --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} https://svn.code.sf.net/p/cbecc-com/code/branches/CBECC-Com_MFamRestructure/ svn-repo
  
    - name: Copy files from SVN to Git
      run: |
        cp -R svn-repo/* git-repo/

    - name: Track Large Files with Git LFS
      run: |
        cd git-repo
        git lfs track "*.bin"
        git lfs track "*.dll"

    - name: Add Pre-Push Hook for Tracking Large Files
      run: |
        cd svn-repo
        echo '#!/bin/sh' > ../git-repo/.git/hooks/pre-push
        echo 'find . -type f -size +50M | grep -v ".git" | xargs -I {} git lfs track "{}"' >> ../git-repo/.git/hooks/pre-push
        echo 'git add .gitattributes' >> ../git-repo/.git/hooks/pre-push
        chmod +x ../git-repo/.git/hooks/pre-push

    - name: Commit SVN to Git
      run: |
        cd git-repo
        git add .
        git commit -m "Mirror from SVN"
        
    - name: Push Git to GitHub
      run: |
        cd git-repo
        git push https://${{ secrets.GIT_USERNAME }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.GIT_USERNAME }}/test-svn-to-git-mirror.git test-mirror-dest --force
