name: Mirror SVN to Git

on:
  workflow_dispatch: # Allows to run manually also

jobs:
  mirrorSVN:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        path: git-repo

    - name: Install SVN
      run: sudo apt-get install -y subversion

    - name: Install Git LFS
      run: |
        sudo apt-get install -y git-lfs
        git lfs install
        
    - name: Configure Checked-Out Git repository
      run: |
        cd git-repo
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
 
    - name: Set Branch Name
      run: |
        echo "BRANCH_NAME=automation-branch-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        echo "Done Setting Name"

    - name: Clone SVN repository
      run: svn checkout --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} https://svn.code.sf.net/p/cbecc-com/code/branches/CBECC-Com_MFamRestructure/ svn-repo
  
    - name: Copy files from SVN to Git
      run: |
        cp -R svn-repo/* git-repo/

    - name: Commit and push SVN to Git If Changes
      run: |
        cd git-repo
        git checkout -b $BRANCH_NAME
        if git diff-index --quiet HEAD --; then
          echo "Nothing to commit"
        else
          git add .
          git commit -m "Mirror from SVN"
          git push origin $BRANCH_NAME
        fi
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: $BRANCH_NAME
        title: "Mirror from SVN"
        body: "This is an automated pull request created by GitHub Actions. Pulled most recent Source Forve SVN Code to new branch."